#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const require = createRequire(import.meta.url);
const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "..");
const OUTPUT_PATH = path.join(ROOT, "src/generated/openapi-types.ts");

async function main() {
  const specPath = require.resolve(
    "@request-suite/request-client-contracts/specs/openapi/request-network-openapi.json"
  );
  const specUrl = pathToFileURL(specPath).href;
  const ast = await openapiTS(specUrl, {
    exportType: true,
    ast: true,
  });

  let output = astToString(ast);

  output = output.replace(
    /agreementStatus: "not_started" \| "completed";/g,
    'agreementStatus: "not_started" | "pending" | "signed" | "completed";'
  );
  output = output.replace(
    /kycStatus: "not_started" \| "completed";/g,
    'kycStatus: "not_started" | "initiated" | "completed";'
  );

  const header =
    "/**\n" +
    " * This file was auto-generated by openapi-typescript.\n" +
    " * Do not make direct changes to the file.\n" +
    " */\n\n";

  await writeFile(OUTPUT_PATH, `${header}${output}\n`);
  console.log(`✅ Generated TypeScript definitions from ${specPath}`);
}

main().catch((error) => {
  console.error("❌ Failed to generate TypeScript types:", error);
  process.exitCode = 1;
});
